import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv("H:\Masters\HenryHarvin\MLwithPython\Crime_Data_from_2020_to_Present.csv")
print('\n------------- head ---------\n')
print(data.head())
print('\n------------- tail ------------------\n')
print(data.tail())
print('\n------------- info ------------------\n')
print(data.info())
print('\n------------- shape brfore dropna ------------------\n')
print(data.shape)
print('\n------------- dropna ------------------\n')
print(data.dropna())
print('\n------------- describe ------------------\n')
print(data.describe())
print('\n------------- isnull().sum() ------------------\n')
print(data.isnull().sum())
print('\n------------- shape ------------------\n')
print(data.shape)
print('\n------------- count duplicate column values ------------------\n')
print(data['DR_NO'].value_counts())
#data['2021'] = np.where(data['2021'] > 0, data['2021'], np.nan)
print('\n------------- mode ------------------\n')
print(data.mode())
print('\n------------- unique ------------------\n')
print(data['AREA'].unique())
print(data.hist(bins=30,figsize=(20,10)))
print('\n------------- Plot ------------------\n')
#plt.plot(data.hist(bins=30,figsize=(20,10)))
#plt.show()